name: bookiee
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  get: ^4.3.8

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/login_screen_pic.png
