name: bookiee
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  syncfusion_flutter_pdfviewer: ^24.2.8

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.7
  get: ^4.3.8

  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.9.0
  animated_theme_switcher: ^2.0.10

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dynamic_curved_navigation_bar: ^0.0.2

  dynamic_height_grid_view: ^0.0.4
  flutter_grid_button: ^2.1.0

  flutter_native_splash: ^2.3.10

  dropdown_textfield: ^1.0.8
  drop_down_search_field: ^1.0.3
  dropdown_button2: ^2.3.9

  carousel_slider: ^4.2.1
  flutter_reorderable_grid_view: ^4.0.0
  griddelegate_fixedcrossaxiscount: ^0.0.1
  provider: ^6.1.2
  device_info_plus: ^9.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/login_screen_pic.png
    - assets/User_Avatar.png
    - assets/icon/actionbook_icon.png
    - assets/icon/audiobook_icon.png
    - assets/icon/classics_icon.png
    - assets/icon/fiction_icon.png
    - assets/icon/Non-fictionbook_icon.png
    - assets/icon/google_icon.png
    - assets/icon/novelbook_icon.png
    - assets/icon/romancebook_icon.png
    - assets/icon/poetry_icon.png
    - assets/icon/crimefiction_book_icon.png
    - assets/icon/thrillerbook_icon.png
    - assets/books/The_Help.jpg
    - assets/books/Dopamine-Detox.jpg
    - assets/books/Hopeless.jpg
    - assets/books/brida.jpg
    - assets/books/The alchemist.jpg
    - assets/books/like the following river.jpg
    - assets/books_pdf/the_help_-_kathryn_stockett.pdf
    - assets/books_pdf/Dopamine Detox.pdf
    - assets/books_pdf/Hopeless.pdf
    - assets/books_pdf/The-Alchemist-PDF-Book-In-English-By-Paulo-Coelho.pdf
    - assets/books_pdf/brida_paulo_chaulo.pdf
    - assets/books_pdf/like_the_following_river.pdf


